name: auth-deploy

on:
  push:
    branches: 
      - master
    paths:
      - 'auth/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t afif1400/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{  secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{  secrets.DOCKER_PASSWORD }} 
      - run: docker push afif1400/auth
