name: orders-deploy

on:
  push:
    branches:
      - master
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && docker build -t afif1400/orders .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{  secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{  secrets.DOCKER_PASSWORD }}
      - run: docker push afif1400/orders
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save gittix-micro
      - run: kubectl rollout restart deployment orders-depl
